<a href="https://colab.research.google.com/github/ultimatecrack/practice/blob/master/Pytorch/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.4122e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.9256e-36]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6274, 0.9822, 0.7464],
        [0.3375, 0.9221, 0.4614],
        [0.4165, 0.3572, 0.6201],
        [0.8447, 0.4262, 0.6166],
        [0.4327, 0.5228, 0.1170]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4732e-03,  8.8481e-01,  1.5011e-01],
        [ 5.6625e-01, -8.4462e-01,  2.0242e+00],
        [-1.3746e+00,  1.3223e+00, -9.5980e-01],
        [-7.0672e-01, -8.9695e-02, -2.4011e+00],
        [ 9.7127e-01,  1.3843e-01,  3.5250e-01]])


Get its size:

In [7]:
print(x.size())

torch.Size([5, 3])


###Torch Operations

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0611,  0.9468,  0.8354],
        [ 1.1518, -0.0865,  2.0978],
        [-0.8216,  2.1749, -0.7981],
        [ 0.2802,  0.1732, -2.1291],
        [ 1.3176,  0.6372,  0.9834]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.0611,  0.9468,  0.8354],
        [ 1.1518, -0.0865,  2.0978],
        [-0.8216,  2.1749, -0.7981],
        [ 0.2802,  0.1732, -2.1291],
        [ 1.3176,  0.6372,  0.9834]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0611,  0.9468,  0.8354],
        [ 1.1518, -0.0865,  2.0978],
        [-0.8216,  2.1749, -0.7981],
        [ 0.2802,  0.1732, -2.1291],
        [ 1.3176,  0.6372,  0.9834]])


Addition: in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.0611,  0.9468,  0.8354],
        [ 1.1518, -0.0865,  2.0978],
        [-0.8216,  2.1749, -0.7981],
        [ 0.2802,  0.1732, -2.1291],
        [ 1.3176,  0.6372,  0.9834]])


**Note:** Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

Resizing: If you want to resize/reshape tensor, you can use **torch.view**:

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5734])
1.573400855064392


###NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


###Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically



In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


###CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.5734], device='cuda:0')
tensor([2.5734], dtype=torch.float64)
